#pragma once
/* ------------------ */

#include <_DISPATCHER_HEADER.h>

//0x18 bytes (sizeof)
struct _KEVENT
{
    struct _DISPATCHER_HEADER Header;                                       //0x0
};
/* Used in */
// _ALPC_PORT
// _ARBITER_INSTANCE
// _CACHE_UNINITIALIZE_EVENT
// _CC_PARTITION
// _CMHIVE
// _DBGK_SILOSTATE
// _DEFERRED_WRITE
// _DEVICE_NODE
// _DEVICE_OBJECT
// _EJOB
// _ESERVERSILO_GLOBALS
// _ETW_REALTIME_CONSUMER
// _EX_WORK_QUEUE
// _EX_WORK_QUEUE_MANAGER
// _FAST_MUTEX
// _FILE_OBJECT
// _HIVE_LIST_ENTRY
// _HIVE_WAIT_PACKET
// _IO_REMOVE_LOCK_COMMON_BLOCK
// _IRP
// _KINTERRUPT
// _KRESOURCEMANAGER
// _KSECONDARY_IDT_ENTRY
// _KTHREAD
// _KTM
// _KTRANSACTION
// _KWAIT_CHAIN_ENTRY
// _LPCP_PORT_OBJECT
// _MI_AVAILABLE_PAGE_WAIT_STATES
// _MI_PARTITION_CORE
// _MI_PARTITION_MODWRITES
// _MI_PARTITION_PAGE_LISTS
// _MI_PARTITION_SEGMENTS
// _MI_PARTITION_STORES
// _MI_PARTITION_ZEROING
// _MI_RESUME_WORKITEM
// _MI_SESSION_STATE
// _MI_SYSTEM_TRIM_STATE
// _MI_SYSTEM_VA_STATE
// _MMINPAGE_SUPPORT
// _MMMOD_WRITER_LISTHEAD
// _MMPAGE_FILE_EXPANSION
// _MM_SESSION_SPACE
// _PALPC_PORT_REFERENCE_WAIT_BLOCK
// _PCW_MASK_INFORMATION
// _PF_KERNEL_GLOBALS
// _PNP_DEVICE_ACTION_ENTRY
// _PNP_DEVICE_EVENT_ENTRY
// _POP_COOLING_EXTENSION
// _POP_DEVICE_SYS_STATE
// _POP_FX_COMPONENT
// _POP_FX_DEVICE
// _POP_FX_PERF_INFO
// _POP_THERMAL_ZONE
// _POP_TRIGGER_WAIT
// _SECONDARY_IC_LIST_ENTRY
// _SHARED_CACHE_MAP
// _UMS_CONTROL_BLOCK
// _WAITING_IRP
// _WHEAP_ERROR_SOURCE_TABLE
// _WMI_LOGGER_CONTEXT
// _WNF_PROCESS_CONTEXT
// _WORK_QUEUE_ENTRY

