#pragma once
/* ------------------ */


//0x4 bytes (sizeof)
struct POHANDLE__
{
    LONG unused;                                                            //0x0
};
/* Used in */
// _HALP_DMA_CONTROLLER
// _PEP_WORK_ACPI_EVALUATE_CONTROL_METHOD_COMPLETE
// _PEP_WORK_ACPI_NOTIFY
// _PEP_WORK_ACTIVE_COMPLETE
// _PEP_WORK_COMPLETE_IDLE_STATE
// _PEP_WORK_COMPLETE_PERF_STATE
// _PEP_WORK_DEVICE_IDLE
// _PEP_WORK_DEVICE_POWER
// _PEP_WORK_IDLE_STATE
// _PEP_WORK_POWER_CONTROL
// _REGISTERED_INTERRUPT_CONTROLLER

